package de.hska.wi.awp.datasource.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.model.Field;
import de.hska.wi.awp.datasource.service.FieldLocalServiceUtil;

/**
 * The extended model base implementation for the Field service. Represents a row in the &quot;jira_Field&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FieldImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FieldImpl
 * @see de.hska.wi.awp.datasource.model.Field
 * @generated
 */
public abstract class FieldBaseImpl extends FieldModelImpl implements Field {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a field model instance should use the {@link Field} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            FieldLocalServiceUtil.addField(this);
        } else {
            FieldLocalServiceUtil.updateField(this);
        }
    }
}
