package de.hska.wi.awp.datasource.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.model.Issue;
import de.hska.wi.awp.datasource.service.IssueLocalServiceUtil;

/**
 * The extended model base implementation for the Issue service. Represents a row in the &quot;jira_Issue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IssueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IssueImpl
 * @see de.hska.wi.awp.datasource.model.Issue
 * @generated
 */
public abstract class IssueBaseImpl extends IssueModelImpl implements Issue {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a issue model instance should use the {@link Issue} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            IssueLocalServiceUtil.addIssue(this);
        } else {
            IssueLocalServiceUtil.updateIssue(this);
        }
    }
}
