package de.hska.wi.awp.datasource.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.model.JiraUser;
import de.hska.wi.awp.datasource.service.JiraUserLocalServiceUtil;

/**
 * The extended model base implementation for the JiraUser service. Represents a row in the &quot;jira_JiraUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JiraUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JiraUserImpl
 * @see de.hska.wi.awp.datasource.model.JiraUser
 * @generated
 */
public abstract class JiraUserBaseImpl extends JiraUserModelImpl
    implements JiraUser {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a jira user model instance should use the {@link JiraUser} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            JiraUserLocalServiceUtil.addJiraUser(this);
        } else {
            JiraUserLocalServiceUtil.updateJiraUser(this);
        }
    }
}
