package de.hska.wi.awp.datasource.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import de.hska.wi.awp.datasource.model.Project;
import de.hska.wi.awp.datasource.model.ProjectModel;
import de.hska.wi.awp.datasource.model.ProjectSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Project service. Represents a row in the &quot;jira_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.hska.wi.awp.datasource.model.ProjectModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectImpl
 * @see de.hska.wi.awp.datasource.model.Project
 * @see de.hska.wi.awp.datasource.model.ProjectModel
 * @generated
 */
@JSON(strict = true)
public class ProjectModelImpl extends BaseModelImpl<Project>
    implements ProjectModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a project model instance should use the {@link de.hska.wi.awp.datasource.model.Project} interface instead.
     */
    public static final String TABLE_NAME = "jira_Project";
    public static final Object[][] TABLE_COLUMNS = {
            { "projectId", Types.VARCHAR },
            { "key_", Types.VARCHAR },
            { "name", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table jira_Project (projectId VARCHAR(75) not null primary key,key_ VARCHAR(75) null,name VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table jira_Project";
    public static final String ORDER_BY_JPQL = " ORDER BY project.projectId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY jira_Project.projectId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.de.hska.wi.awp.datasource.model.Project"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.de.hska.wi.awp.datasource.model.Project"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.de.hska.wi.awp.datasource.model.Project"),
            true);
    public static long KEY_COLUMN_BITMASK = 1L;
    public static long PROJECTID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.de.hska.wi.awp.datasource.model.Project"));
    private static ClassLoader _classLoader = Project.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Project.class
        };
    private String _projectId;
    private String _key;
    private String _originalKey;
    private String _name;
    private long _columnBitmask;
    private Project _escapedModel;

    public ProjectModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Project toModel(ProjectSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Project model = new ProjectImpl();

        model.setProjectId(soapModel.getProjectId());
        model.setKey(soapModel.getKey());
        model.setName(soapModel.getName());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Project> toModels(ProjectSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Project> models = new ArrayList<Project>(soapModels.length);

        for (ProjectSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public String getPrimaryKey() {
        return _projectId;
    }

    @Override
    public void setPrimaryKey(String primaryKey) {
        setProjectId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _projectId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey((String) primaryKeyObj);
    }

    @Override
    public Class<?> getModelClass() {
        return Project.class;
    }

    @Override
    public String getModelClassName() {
        return Project.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("projectId", getProjectId());
        attributes.put("key", getKey());
        attributes.put("name", getName());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String projectId = (String) attributes.get("projectId");

        if (projectId != null) {
            setProjectId(projectId);
        }

        String key = (String) attributes.get("key");

        if (key != null) {
            setKey(key);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }
    }

    @JSON
    @Override
    public String getProjectId() {
        if (_projectId == null) {
            return StringPool.BLANK;
        } else {
            return _projectId;
        }
    }

    @Override
    public void setProjectId(String projectId) {
        _projectId = projectId;
    }

    @JSON
    @Override
    public String getKey() {
        if (_key == null) {
            return StringPool.BLANK;
        } else {
            return _key;
        }
    }

    @Override
    public void setKey(String key) {
        _columnBitmask |= KEY_COLUMN_BITMASK;

        if (_originalKey == null) {
            _originalKey = _key;
        }

        _key = key;
    }

    public String getOriginalKey() {
        return GetterUtil.getString(_originalKey);
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public Project toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Project) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        ProjectImpl projectImpl = new ProjectImpl();

        projectImpl.setProjectId(getProjectId());
        projectImpl.setKey(getKey());
        projectImpl.setName(getName());

        projectImpl.resetOriginalValues();

        return projectImpl;
    }

    @Override
    public int compareTo(Project project) {
        String primaryKey = project.getPrimaryKey();

        return getPrimaryKey().compareTo(primaryKey);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Project)) {
            return false;
        }

        Project project = (Project) obj;

        String primaryKey = project.getPrimaryKey();

        if (getPrimaryKey().equals(primaryKey)) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey().hashCode();
    }

    @Override
    public void resetOriginalValues() {
        ProjectModelImpl projectModelImpl = this;

        projectModelImpl._originalKey = projectModelImpl._key;

        projectModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Project> toCacheModel() {
        ProjectCacheModel projectCacheModel = new ProjectCacheModel();

        projectCacheModel.projectId = getProjectId();

        String projectId = projectCacheModel.projectId;

        if ((projectId != null) && (projectId.length() == 0)) {
            projectCacheModel.projectId = null;
        }

        projectCacheModel.key = getKey();

        String key = projectCacheModel.key;

        if ((key != null) && (key.length() == 0)) {
            projectCacheModel.key = null;
        }

        projectCacheModel.name = getName();

        String name = projectCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            projectCacheModel.name = null;
        }

        return projectCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(7);

        sb.append("{projectId=");
        sb.append(getProjectId());
        sb.append(", key=");
        sb.append(getKey());
        sb.append(", name=");
        sb.append(getName());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(13);

        sb.append("<model><model-name>");
        sb.append("de.hska.wi.awp.datasource.model.Project");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>projectId</column-name><column-value><![CDATA[");
        sb.append(getProjectId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>key</column-name><column-value><![CDATA[");
        sb.append(getKey());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
