package de.hska.wi.awp.datasource.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.model.Status;
import de.hska.wi.awp.datasource.service.StatusLocalServiceUtil;

/**
 * The extended model base implementation for the Status service. Represents a row in the &quot;jira_Status&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StatusImpl
 * @see de.hska.wi.awp.datasource.model.Status
 * @generated
 */
public abstract class StatusBaseImpl extends StatusModelImpl implements Status {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a status model instance should use the {@link Status} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            StatusLocalServiceUtil.addStatus(this);
        } else {
            StatusLocalServiceUtil.updateStatus(this);
        }
    }
}
