package de.hska.wi.awp.datasource.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the IssueType service. Represents a row in the &quot;jira_IssueType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.model.impl.IssueTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.model.impl.IssueTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IssueType
 * @see de.hska.wi.awp.datasource.model.impl.IssueTypeImpl
 * @see de.hska.wi.awp.datasource.model.impl.IssueTypeModelImpl
 * @generated
 */
public interface IssueTypeModel extends BaseModel<IssueType> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a issue type model instance should use the {@link IssueType} interface instead.
     */

    /**
     * Returns the primary key of this issue type.
     *
     * @return the primary key of this issue type
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this issue type.
     *
     * @param primaryKey the primary key of this issue type
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the issue ID of this issue type.
     *
     * @return the issue ID of this issue type
     */
    @AutoEscape
    public String getIssueId();

    /**
     * Sets the issue ID of this issue type.
     *
     * @param issueId the issue ID of this issue type
     */
    public void setIssueId(String issueId);

    /**
     * Returns the issue name of this issue type.
     *
     * @return the issue name of this issue type
     */
    @AutoEscape
    public String getIssueName();

    /**
     * Sets the issue name of this issue type.
     *
     * @param issueName the issue name of this issue type
     */
    public void setIssueName(String issueName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(de.hska.wi.awp.datasource.model.IssueType issueType);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.model.IssueType> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.model.IssueType toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.model.IssueType toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
