package de.hska.wi.awp.datasource.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the IssuePriority service. Represents a row in the &quot;jira_IssuePriority&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.model.impl.IssuePriorityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.model.impl.IssuePriorityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IssuePriority
 * @see de.hska.wi.awp.datasource.model.impl.IssuePriorityImpl
 * @see de.hska.wi.awp.datasource.model.impl.IssuePriorityModelImpl
 * @generated
 */
public interface IssuePriorityModel extends BaseModel<IssuePriority> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a issue priority model instance should use the {@link IssuePriority} interface instead.
     */

    /**
     * Returns the primary key of this issue priority.
     *
     * @return the primary key of this issue priority
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this issue priority.
     *
     * @param primaryKey the primary key of this issue priority
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the priority ID of this issue priority.
     *
     * @return the priority ID of this issue priority
     */
    public long getPriorityId();

    /**
     * Sets the priority ID of this issue priority.
     *
     * @param priorityId the priority ID of this issue priority
     */
    public void setPriorityId(long priorityId);

    /**
     * Returns the priority name of this issue priority.
     *
     * @return the priority name of this issue priority
     */
    @AutoEscape
    public String getPriorityName();

    /**
     * Sets the priority name of this issue priority.
     *
     * @param priorityName the priority name of this issue priority
     */
    public void setPriorityName(String priorityName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        de.hska.wi.awp.datasource.model.IssuePriority issuePriority);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.model.IssuePriority> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.model.IssuePriority toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.model.IssuePriority toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
