package de.hska.wi.awp.datasource.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Issue service. Represents a row in the &quot;jira_Issue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.model.impl.IssueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.model.impl.IssueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Issue
 * @see de.hska.wi.awp.datasource.model.impl.IssueImpl
 * @see de.hska.wi.awp.datasource.model.impl.IssueModelImpl
 * @generated
 */
public interface IssueModel extends BaseModel<Issue> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a issue model instance should use the {@link Issue} interface instead.
     */

    /**
     * Returns the primary key of this issue.
     *
     * @return the primary key of this issue
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this issue.
     *
     * @param primaryKey the primary key of this issue
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the issue ID of this issue.
     *
     * @return the issue ID of this issue
     */
    @AutoEscape
    public String getIssueId();

    /**
     * Sets the issue ID of this issue.
     *
     * @param issueId the issue ID of this issue
     */
    public void setIssueId(String issueId);

    /**
     * Returns the key of this issue.
     *
     * @return the key of this issue
     */
    @AutoEscape
    public String getKey();

    /**
     * Sets the key of this issue.
     *
     * @param key the key of this issue
     */
    public void setKey(String key);

    /**
     * Returns the self of this issue.
     *
     * @return the self of this issue
     */
    @AutoEscape
    public String getSelf();

    /**
     * Sets the self of this issue.
     *
     * @param self the self of this issue
     */
    public void setSelf(String self);

    /**
     * Returns the field ID of this issue.
     *
     * @return the field ID of this issue
     */
    public long getFieldId();

    /**
     * Sets the field ID of this issue.
     *
     * @param fieldId the field ID of this issue
     */
    public void setFieldId(long fieldId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(de.hska.wi.awp.datasource.model.Issue issue);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.model.Issue> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.model.Issue toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.model.Issue toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
