package de.hska.wi.awp.datasource.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the JiraUser service. Represents a row in the &quot;jira_JiraUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.model.impl.JiraUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.model.impl.JiraUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JiraUser
 * @see de.hska.wi.awp.datasource.model.impl.JiraUserImpl
 * @see de.hska.wi.awp.datasource.model.impl.JiraUserModelImpl
 * @generated
 */
public interface JiraUserModel extends BaseModel<JiraUser> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a jira user model instance should use the {@link JiraUser} interface instead.
     */

    /**
     * Returns the primary key of this jira user.
     *
     * @return the primary key of this jira user
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this jira user.
     *
     * @param primaryKey the primary key of this jira user
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the creator ID of this jira user.
     *
     * @return the creator ID of this jira user
     */
    @AutoEscape
    public String getCreatorId();

    /**
     * Sets the creator ID of this jira user.
     *
     * @param creatorId the creator ID of this jira user
     */
    public void setCreatorId(String creatorId);

    /**
     * Returns the displayname of this jira user.
     *
     * @return the displayname of this jira user
     */
    @AutoEscape
    public String getDisplayname();

    /**
     * Sets the displayname of this jira user.
     *
     * @param displayname the displayname of this jira user
     */
    public void setDisplayname(String displayname);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(de.hska.wi.awp.datasource.model.JiraUser jiraUser);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.model.JiraUser> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.model.JiraUser toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.model.JiraUser toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
