package de.hska.wi.awp.datasource.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Project service. Represents a row in the &quot;jira_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.model.impl.ProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.model.impl.ProjectImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Project
 * @see de.hska.wi.awp.datasource.model.impl.ProjectImpl
 * @see de.hska.wi.awp.datasource.model.impl.ProjectModelImpl
 * @generated
 */
public interface ProjectModel extends BaseModel<Project> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a project model instance should use the {@link Project} interface instead.
     */

    /**
     * Returns the primary key of this project.
     *
     * @return the primary key of this project
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this project.
     *
     * @param primaryKey the primary key of this project
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the project ID of this project.
     *
     * @return the project ID of this project
     */
    @AutoEscape
    public String getProjectId();

    /**
     * Sets the project ID of this project.
     *
     * @param projectId the project ID of this project
     */
    public void setProjectId(String projectId);

    /**
     * Returns the key of this project.
     *
     * @return the key of this project
     */
    @AutoEscape
    public String getKey();

    /**
     * Sets the key of this project.
     *
     * @param key the key of this project
     */
    public void setKey(String key);

    /**
     * Returns the name of this project.
     *
     * @return the name of this project
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this project.
     *
     * @param name the name of this project
     */
    public void setName(String name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(de.hska.wi.awp.datasource.model.Project project);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.model.Project> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.model.Project toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.model.Project toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
