package de.hska.wi.awp.datasource.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Status service. Represents a row in the &quot;jira_Status&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.model.impl.StatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.model.impl.StatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Status
 * @see de.hska.wi.awp.datasource.model.impl.StatusImpl
 * @see de.hska.wi.awp.datasource.model.impl.StatusModelImpl
 * @generated
 */
public interface StatusModel extends BaseModel<Status> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a status model instance should use the {@link Status} interface instead.
     */

    /**
     * Returns the primary key of this status.
     *
     * @return the primary key of this status
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this status.
     *
     * @param primaryKey the primary key of this status
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the status ID of this status.
     *
     * @return the status ID of this status
     */
    public long getStatusId();

    /**
     * Sets the status ID of this status.
     *
     * @param statusId the status ID of this status
     */
    public void setStatusId(long statusId);

    /**
     * Returns the name of this status.
     *
     * @return the name of this status
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this status.
     *
     * @param name the name of this status
     */
    public void setName(String name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(de.hska.wi.awp.datasource.model.Status status);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.model.Status> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.model.Status toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.model.Status toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
