package de.hska.wi.awp.datasource.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Student service. Represents a row in the &quot;jira_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.model.impl.StudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.model.impl.StudentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Student
 * @see de.hska.wi.awp.datasource.model.impl.StudentImpl
 * @see de.hska.wi.awp.datasource.model.impl.StudentModelImpl
 * @generated
 */
public interface StudentModel extends BaseModel<Student> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link Student} interface instead.
     */

    /**
     * Returns the primary key of this student.
     *
     * @return the primary key of this student
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this student.
     *
     * @param primaryKey the primary key of this student
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the student ID of this student.
     *
     * @return the student ID of this student
     */
    public long getStudentId();

    /**
     * Sets the student ID of this student.
     *
     * @param studentId the student ID of this student
     */
    public void setStudentId(long studentId);

    /**
     * Returns the first name of this student.
     *
     * @return the first name of this student
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this student.
     *
     * @param firstName the first name of this student
     */
    public void setFirstName(String firstName);

    /**
     * Returns the last name of this student.
     *
     * @return the last name of this student
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this student.
     *
     * @param lastName the last name of this student
     */
    public void setLastName(String lastName);

    /**
     * Returns the student age of this student.
     *
     * @return the student age of this student
     */
    public int getStudentAge();

    /**
     * Sets the student age of this student.
     *
     * @param studentAge the student age of this student
     */
    public void setStudentAge(int studentAge);

    /**
     * Returns the student gender of this student.
     *
     * @return the student gender of this student
     */
    public int getStudentGender();

    /**
     * Sets the student gender of this student.
     *
     * @param studentGender the student gender of this student
     */
    public void setStudentGender(int studentGender);

    /**
     * Returns the student address of this student.
     *
     * @return the student address of this student
     */
    @AutoEscape
    public String getStudentAddress();

    /**
     * Sets the student address of this student.
     *
     * @param studentAddress the student address of this student
     */
    public void setStudentAddress(String studentAddress);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(de.hska.wi.awp.datasource.model.Student student);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.model.Student> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.model.Student toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.model.Student toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
